#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /opt/WaterWolf/waterwolf 80
    chown root /opt/WaterWolf/chrome-sandbox
    chmod 4755 /opt/WaterWolf/chrome-sandbox
    echo "Run sudo xdg-settings set default-web-browser waterwolf.desktop && sudo update-alternatives --config x-www-browser to set WaterWolf as your default browser."
    ln -sf /opt/WaterWolf/waterwolf /usr/bin/waterwolf
fi
